// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadModel(arg1, arg2) {
  return window['go']['backend']['App']['DownloadModel'](arg1, arg2);
}

export function ListModels() {
  return window['go']['backend']['App']['ListModels']();
}

export function LoadModelOnly(arg1) {
  return window['go']['backend']['App']['LoadModelOnly'](arg1);
}

export function StartChat(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['backend']['App']['StartChat'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function StopChat() {
  return window['go']['backend']['App']['StopChat']();
}
