// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DownloadModel(arg1:string,arg2:string):Promise<string>;

export function ListModels():Promise<Array<models.ModelInfo>>;

export function StartChat(arg1:string,arg2:string,arg3:number):Promise<string>;

export function StopChat():Promise<void>;
